services:
  openobserve:
    image: openobserve/openobserve:latest
    container_name: openobserve.localenv.io
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - ZO_TELEMETRY=false
      - ZO_ROOT_USER_EMAIL=admin@localenv.io
      - ZO_ROOT_USER_PASSWORD=SuperPass#
      - ZO_DATA_DIR=/data
    ports:
      - "5080:5080"
      - "5081:5081"
    networks:
      default:
        aliases:
          - openobserve.localenv.io
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openobserve.rule=Host(`openobserve.localenv.io`)"
      - "traefik.http.routers.openobserve.entrypoints=web"
      - "traefik.http.services.openobserve.loadbalancer.server.port=5080"
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - openobserve_data:/data


volumes: 
  openobserve_data: